Deployer enabled
hemilabs/safe-infrastructure pull request #2
Opened 2024-07-04 00:01 UTC by dhidalgX

@gabmontes Could we approve this PR before deploying the latest commit? 
Theres some ENV variables i have added to they wont get overwritten and also enabling the deployer.

Thanks!

2024-07-04 13:49 UTC, gabmontes requested changes

2024-07-04 13:49 UTC, gabmontes commented on .env.sample
> +CFG_VERSION=v2.82.0
```suggestion
CFG_VERSION=staging
```

2024-07-04 13:49 UTC, gabmontes commented on container_env_files/cfg.env
> +MEDIA_URL = "https://safe.hemi.xyz/cfg/media/"
```suggestion
# MEDIA_URL = "http://localhost:8000/cfg/media/"

MEDIA_BASE_URL = "https://safe.hemi.xyz/cfg/media/"
```

2024-07-04 13:49 UTC, gabmontes commented on container_env_files/cgw.env
Let's revert all the changes to this file except for the line defining `AUTH_TOKEN`.

2024-07-04 14:51 UTC, dhidalgX commented on container_env_files/cgw.env
updated

2024-07-05 17:06 UTC, gabmontes approved these changes

2024-07-05 17:34 UTC, merged